name: Publish Package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    name: Publish
    uses: JagandeepBrar/github-dart-workflows/.github/workflows/deploy-dart-package.yml@main
